name: Wails build

on:
  release:
    types: [created]

permissions:
 contents: write
 packages: write

env:
  BINARY_PREFIX: "bili-FM"
  BINARY_SUFFIX: ""

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {platform: linux/amd64, os: ubuntu-latest, goos: linux, goarch: amd64},
          {platform: windows/amd64, os: windows-latest, goos: windows, goarch: amd64},
          {platform: darwin/amd64, os: macos-latest, goos: darwin, goarch: amd64},
          {platform: darwin/arm64, os: macos-latest, goos: darwin, goarch: arm64}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
      - name: install pnpm
        run: npm install -g pnpm
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ env.BINARY_PREFIX }}
          build-platform: ${{ matrix.build.platform }}
          package: false
      - name: zip binary
        env:
          GOOS: ${{ matrix.build.goos }}
          GOARCH: ${{ matrix.build.goarch }}
        run: |
          if [ $GOOS == "windows" ]; then export BINARY_SUFFIX=".exe"; fi
          if [ $GOOS == "darwin" ]; then export BINARY_SUFFIX=".app"; fi
          cd "$GITHUB_WORKSPACE/build/bin"
          rm -f ./*.zip
          export BINARY_NAME="$BINARY_PREFIX$BINARY_SUFFIX"
          zip "$BINARY_PREFIX_$GOOS_$GOARCH.zip" "$BINARY_NAME"

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bin/${{ env.BINARY_PREFIX }}*.zip*
          overwrite: true
          file_glob: true
        