on:
  release:
    types: [created]

permissions:
 contents: write
 packages: write

env:
  BINARY_PREFIX: "biliFM"
  BINARY_SUFFIX: ""
  LD_FLAGS: "-w -s"
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - name: "biliFM"
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'biliFM'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'biliFM'
            platform:  'darwin/universal'
            os: 'macos-latest'
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Build wails
        uses: dAppServer/wails-build-action@v3
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.24.3'
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bin/${{ env.BINARY_PREFIX }}*
          overwrite: true
          file_glob: true